### ISSUE TITLE
Increasing GPU memory in sac code

### ISSUE THREAD

**Issue by ShahRutav** [ShahRutav/torchrl_examples#4]
The GPU memory keeps increasing if we do not explicitly collect the generation using `gc.collect` while running `sac.py`
Example is [here](https://github.com/ShahRutav/torchrl_examples/blob/a6349da9efa273761bf80b3b257b5d842218e8f4/sac_mujoco/sac.py#L446)

Can this be handled internally in torchRL?

**Comment by vmoens** [comment]
Will look into this. Can you open the same issue on torchrl?

**Comment by ShahRutav** [comment]
https://github.com/pytorch/rl/issues/834
